    //const char *fname =  "/afs//cern.ch/work/j/jmartinb/public/Datasets/pPb2016/Forest/Data/285090"; //merged
    const char *fname =  "/afs/cern.ch/work/q/qixu/public/centrality/Run2Prep/pPbData"; //merged
    const char *histoname = "mergeskim_pPb_28509";
    const int nfilter = 6;
    const int startpoint = 0;
    const int nfile = 1;
    const char* evtfilter[] = {"((lumi>60 && lumi<132) || (lumi>135 && lumi<201) || (lumi>261 && lumi<369))","HLT_PAL1MinimumBiasHF_AND_SinglePixelTrack_v1","pBeamScrapingFilter","pPAprimaryVertexFilter","pVertexFilterCutGplus","phfCoincFilter1"};
    const char* evtfiltershort[] = {"Good lumi","MBTrig","BeamScraping","Vertex","PileUp","HFCoin1"};
    const char* evtfilteraccushort[] = {"Good lumi","MBTrig","MBTrig_BeamScraping","Trig_BS_VF","Trig_BS_VF_PU","Trig_BS_VF_PU_HFC1"};
    const char* trig = evtfilter[1];
    TCut cut = evtfilter[1];
    const TString type="Run 285090 5TeV pPb";
